=== iliashenkoa/bus_net/simulation-busnet/target/classes/start_configuration/schema/config.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0"
	xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="configuration" type="network-config" />

	<xs:complexType name="network-config">
		<xs:sequence>
			<xs:element name="buses-capacity" type="xs:int" />
			<xs:element name="buses-speed" type="speed-type" />
			<xs:element name="buses-count-per-route" type="xs:int" />
			<xs:element name="simulation-start-time" type="time"
				minOccurs="0" />
			<xs:element name="simulation-end-time" type="time"
				minOccurs="0" />
			<xs:element name="time-acceleration-coeff"
				type="xs:double" />
		</xs:sequence>
	</xs:complexType>

	<xs:simpleType name="speed-type">
		<xs:restriction base="xs:double">
			<xs:minInclusive value="20.0" />
			<xs:maxInclusive value="60.0" />
	</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="time">
		<xs:sequence>
			<xs:element name="year" type="xs:int" />
			<xs:element name="month" type="xs:int" />
			<xs:element name="day" type="xs:int" />
			<xs:element name="hours" type="xs:int" />
			<xs:element name="minutes" type="xs:int" />
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== iliashenkoa/bus_net/simulation-busnet/src/main/resources/start_configuration/configuration.xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="schema/config.xsd">
	<buses-capacity>40</buses-capacity>
	<buses-speed>45.0</buses-speed>
	<buses-count-per-route>15</buses-count-per-route>
	<simulation-start-time>
		<year>2019</year>
		<month>3</month>
		<day>1</day>
		<hours>7</hours>
		<minutes>30</minutes>
	</simulation-start-time>
	<simulation-end-time>
		<year>2019</year>
		<month>3</month>
		<day>3</day>
		<hours>9</hours>
		<minutes>50</minutes>
	</simulation-end-time>
	<time-acceleration-coeff>30000.0</time-acceleration-coeff>
</configuration>
